### ISSUE TITLE
Move this repo to https://github.com/jakartaee

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/expression-language#181]
In the steering committee we voted to moved all specification projects from eclipse-ee4j to jakartaee. As such this repo should move too in due time.

Moving is fairly automatic, and redirects will be automatically put in place from the current location here to the new location.

If there are no objections I'd like to move this repo soon.

**Comment by markt-asf** [comment]
No objections from me. I would ask that the name is changed to jakartaee/el-api

**Comment by pzygielo** [comment]
>  I would ask that the name is changed to jakartaee/el-api

Projects in https://github.com/jakartaee/ do not seem to have `-api` suffix, even when they do provide them:
- https://github.com/jakartaee/authorization
- https://github.com/jakartaee/authentication
- https://github.com/jakartaee/websocket
- https://github.com/jakartaee/messaging

So perhaps the name could be changed to something else?

**Comment by markt-asf** [comment]
el or expression-language would be OK by me

**Comment by arjantijms** [comment]
> el or expression-language would be OK by me

I went for the latter. Thanks for everyone's input and help!
