### ISSUE TITLE
There should be a public milestone release

### ISSUE THREAD

**Issue by starksm64** [jakartaee/expression-language#182]
Based on the platform group discussion today, at least one of the milestones in staging should be made public so other downstream dependencies can make public releases. The latest milestone prior to the current 5.0.0 final was 5.0.0-M3:
https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/el/jakarta.el-api/5.0.0-M3/

Could someone release that to maven central?

**Comment by arjantijms** [comment]
I can push it to central, but I'm just curious; why can't the downstream dependencies not update to 5.0.0 instead?

**Comment by arjantijms** [comment]
RC1 (from https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/el/jakarta.el-api/5.0.0-RC1/) has been pushed to central.

**Comment by arjantijms** [comment]
And it already arrived there: https://repo1.maven.org/maven2/jakarta/el/jakarta.el-api/5.0.0-RC1/

**Comment by markt-asf** [comment]
This means we have an 5.0.0-RC1 release that is based of a later revision than the 5.0.0 version currently under release review. Is that wise?

**Comment by arjantijms** [comment]
I just checked, and this commit was not yet in 5.0.0 as staged:

https://github.com/jakartaee/expression-language/commit/06dc4b44d1bbe5722a590703c996ec0fd8e67342#diff-14c2529eb4498c5d1ffd6915d05bf58a91bdda796af59f41d480d11c099d0479

But should we even release 5.0.0 without that?

**Comment by markt-asf** [comment]
It should be? The 5.0.0-RELEASE-api tag was made immediately after that commit. Are you looking at an out of date tag?

**Comment by markt-asf** [comment]
There isn't anything, yet, that I can see in the commit history post the 5.0.0 tag that would justify re-rolling 5.0.0. Of course, if the release review identifies any issues we'll need to re-roll 5.0.0 anyway.

**Comment by starksm64** [comment]
It makes it awkward to have other releases pushed to maven central that have dependencies on EL which has no 5.0.x release out there. I'm not looking for a new release, just a release of an existing non-final 5.0.x release in staging released to central.

**Comment by arjantijms** [comment]
> It should be. The 5.0.0-RELEASE-api tag was made immediately after that commit.

I downloaded the artefact from staging and it source jar had this in it:

```java
/*
 * Copyright (c) 2021 Contributors to the Eclipse Foundation
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */
module jakarta.el {
    exports jakarta.el;

    requires transitive java.desktop;
}
```

**Comment by markt-asf** [comment]
Hmm. Something isn't right here. Time to do some digging.

**Comment by arjantijms** [comment]
Indeed, plus, the ballot for expression language hasn't started yet, has it?

**Comment by arjantijms** [comment]
The PR is still in progress, and the list at https://www.eclipse.org/lists/jakarta.ee-spec/2022/Jan/index.html doesn't mention any start of the ballot. It seems we should be good to still update and/or re-stage 5.0.0.

**Comment by starksm64** [comment]
No not started yet as the PR is still in the review stage.
https://github.com/jakartaee/specifications/pull/429

**Comment by markt-asf** [comment]
Mystery mostly solved. It appears that the CI build isn't dropping the existing staged even when configured to do so. Nexus shows the oldest version available in the file browser rather than the newest - hence we see the old version.

I've dropped the old staged versions and I'll look into why the CI build isn't doing what we expect.

**Comment by arjantijms** [comment]
> Nexus shows the oldest version available in the file browser rather than the newest - hence we see the old version.

You're right, I just noticed that too. There were staged 5.0.0 versions.

**Comment by starksm64** [comment]
I think that is the normal default behavior. You have to drop an existing release in order for the newer build to show up.
