### ISSUE TITLE
Compatibility certification request for Expressly

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/expression-language#185]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [Eclipse Expressly 5.0.0-M2](https://github.com/eclipse-ee4j/expressly)
- [x] Specification Name, Version and download URL
   [Jakarta Expression Language 5.0](https://jakarta.ee/specifications/expression-language/5.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Expression Language TCK 5.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-expression-language-tck-5.0.0.zip), SHA-256: `6ac4057c4c2151fe2856379ec682fd996042a2ff2db9dd44962bcd3a9ecb2bbf`
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://glassfish.org/certifications/jakarta-expression-language/5.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  OpenJDK 11.0.2, 17.0.1, 18-ea
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Debian GNU/Linux 10
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by markt-asf** [comment]
Approved.
