### ISSUE TITLE
Jakarta Expression Language 5.0 Release

### ISSUE THREAD

**Issue by Pandrex247** [jakartaee/expression-language#186]
- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by markt-asf** [comment]
I've promoted the EL 5.0.0 and it is there on Maven Central but hasn't been indexed so it isn't showing up in searches. I'll check that task off once indexing is complete.

We don't need to merge any release branches but we do need to update the version number. My assumption is that the next version will be 6.0 as we want to remove some code deprecated in 5.0. I'll check that task off once the version has been updated.

@arjantijms Can you send the TCK email?

**Comment by markt-asf** [comment]
Maven index is complete

**Comment by arjantijms** [comment]
Mail has been send.

**Comment by arjantijms** [comment]
All done.
