### ISSUE TITLE
Address permission checks when running under Security Manager -- Next

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/expression-language#192]
The Security Manager is deprecated for removal, and for EL.Next (Jakarta EE 11) we should remove all references to it from our code.

**Comment by markt-asf** [comment]
Has it been confirmed that SecurityManager support is to be removed in Jakarta EE 11? I haven't seen any such announcement but may have missed it.

**Comment by markt-asf** [comment]
It has been [announced](https://www.eclipse.org/lists/jakartaee-platform-dev/msg03898.html) this week that Jakarta EE 11 will target Java 21.
Given the above, I agree with the plan to remove all references to the SecurityManager. I'll create a PR to do that shortly.

**Comment by markt-asf** [comment]
See #193

**Comment by markt-asf** [comment]
Fixed in #193.
