### ISSUE TITLE
Expression Language 6.0.0 Release

### ISSUE THREAD

**Issue by Pandrex247** [jakartaee/expression-language#213]
Please address the following checklist for finalising the release of Expression Language 6.0.0
 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] (N/A) if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

Original Specifications repo release PR: https://github.com/jakartaee/specifications/pull/701

**Comment by markt-asf** [comment]
All tasks completed.
